
name: nightly-refresh
on:
  schedule:
    - cron: '0 14 * * *'
jobs:
  full:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          MAX_COMPANIES_PER_RUN: 500
        run: python fetch_signals.py
